export const URL_INPUT_UPDATE = "URL_INPUT_UPDATE";
export const GENERATE_URL = "GENERATE_URL";
export const URL_GENERATED = "URL_GENERATED";
export const URL_GENERATED_ERROR = "URL_GENERATED_ERROR";
